In [3]:
import numpy as np

## create array 
#1 d array

arr1= np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2=np.array([[1,2,3]])
arr2.shape

(1, 3)

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr1.dtype

dtype('int64')

In [18]:
## Vectorized operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])


print("Addition", arr1+arr2)

print("Subtraction", arr2-arr1)

print("Multiplication", arr1*arr2)

print("Division", arr2/arr1)

Addition [11 22 33 44 55]
Subtraction [ 9 18 27 36 45]
Multiplication [ 10  40  90 160 250]
Division [10. 10. 10. 10. 10.]


In [19]:
## Universal functions

arr=np.array([2,3,4,5])

print("Square root", np.sqrt(arr))

Square root [1.41421356 1.73205081 2.         2.23606798]


In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[0][0]

np.int64(1)

In [24]:
arr[1:,2:]

array([[6],
       [9]])